### PR TITLE
Fix interactive plot legend and color code for facet plot

### LINKED ISSUE #46: Legend and color code incorrect for "facet" plot with missing value
if a plot is created with 4 model_id, projecting 5 locations and one team has not submit all the locations:
- if the first plot does not have all the 4 teams, one will be missing from the legend
- the color associated with each team might not be respected and some models might have mix color.

### PR DESCRIPTION
**Pull request by LucieContamin**
fixes #46 

- create legend after plot generated to add all expected trace in the legend
- transform the `fill_by` column as a factor (internally) to unsure the palette is assigned properly

### CODE REVIEW

File: tests/testthat/test-plot_step_ahead_model_output.R [hunk 1]
```diff
@@ -204,6 +208,45 @@ test_that("Output", {
...
+  plot_test <-
+    plot_step_ahead_model_output(test_data,
+                                 target_data_us,
+                                 use_median_as_point = TRUE,
+                                 facet = "scenario_id")
+  leg_sel <- !unlist(purrr::map(purrr::map(plot_test$x$data, "showlegend"),
+                                isFALSE))
+  legend <- unique(unlist(purrr::map(purrr::map(plot_test$x$data,
+                                                "name")[leg_sel],
+                                     as.character)))
```
Comment (zkamvar) [inline tests/testthat/test-plot_step_ahead_model_output.R:225]: You can use the underscore functions to extract these values instead of a double-map. This makes the code a bit easier to reason about when coming back to it. 

```suggestion
  leg_sel <- purrr::map_lgl(plot_test$x$data, "showlegend")
  legend <- purrr::map_chr(plot_test$x$data, \(x) as.character(x$name))[leg_sel]
```

File: tests/testthat/test-plot_step_ahead_model_output.R [hunk 2]
```diff
@@ -204,6 +208,45 @@ test_that("Output", {
...
```
Comment (zkamvar) [inline tests/testthat/test-plot_step_ahead_model_output.R:246]:
```suggestion
  leg_sel <- purrr::map_lgl(plot_test$x$data, "showlegend")
  legend <- purrr::map_chr(plot_test$x$data, \(x) as.character(x$name))[leg_sel]
```

File: R/subplot_utils.R [hunk 3]
```diff
@@ -353,6 +347,15 @@ plotly_subplot <- function(plot_model, all_plot, all_ens, facet,
                     ens_name = ens_name, group = group, ens_color = ens_color)
   plot_model <- plotly::subplot(subplot, nrows = facet_nrow, shareX = sharex,
                                 shareY = sharey)
+  exp_legend <- unlist(unique(purrr::map(purrr::map(all_plot, fill_by),
+                                         levels)))
```
Comment (zkamvar) [inline R/subplot_utils.R:351]:
```suggestion
  exp_legend <- unlist(unique(purrr::map(all_plot, \(x) levels(x[[fill_by]]))))
```

File: R/subplot_utils.R [hunk 4]
```diff
@@ -353,6 +347,15 @@ plotly_subplot <- function(plot_model, all_plot, all_ens, facet,
...
+  if (plot_target) exp_legend <- c("target", exp_legend)
+  for (i in seq_along(exp_legend)) {
+    vis_leg_sel <- grep(TRUE,
```
Comment (zkamvar) [inline R/subplot_utils.R:354]:
```suggestion
    # find the first matching element and make sure that element is shown in the legend
    vis_leg_sel <- grep(TRUE,
```

File: NEWS.md [hunk 5]
```diff
@@ -1,3 +1,12 @@
+# hubVis 0.1.1
+
+This release contains an update to fix issue #46:
+
+- create legend after plot generated to add all expected trace in the legend
+- transform the fill_by column as a factor (internally) to unsure the palette
```
Comment (zkamvar) [inline NEWS.md:6]:
```suggestion
- transform the fill_by column as a factor (internally) to ensure the palette 
```

**Review by zkamvar — APPROVED** [review]
This looks good to me. I've made non-blocking suggestions to simplify the code and add comments as to what's happening, but otherwise it's good to go.
