### PR TITLE
Fix shared axis on interactive plot

### LINKED ISSUE #60: Interactive Zoom behavior
The zoom options on the plotly interactive version of the plot is not working as expected when all axis are shared.

### PR DESCRIPTION
**Pull request by LucieContamin**
- fix shared axis on interactive plot version (fix zoom issue)

Closes #60

### CODE REVIEW

**Review by annakrystalli — CHANGES_REQUESTED** [review]
Nice work @LucieContamin !

This all looks sensible at first pass to me although I think some very minor refactoring and additional comments/fn documentation would make understanding what's going on much easier.

The biggest issue for me is that there are no tests for the new functionality. Could you please add a few?

File: R/scatter_plot_utils.R [hunk 1]
```diff
@@ -398,3 +399,105 @@ simple_model_plot <- function(
...
+#' @param plot_model a plot_ly or ggplot object
+#' @param attribute_name string, name or regex of the name of attribute(s) to
+#' update, extracted from the layout of the plot.
+#' @param attributes list, new attributes to add in the `layoutAttrs` of the
+#' plot (for example, `list(type = "log")` to transform axis to log scale)
+#'
+#' @noRd
+#' @importFrom purrr map
+plot_model_layout_attr <- function(plot_model, attribute_name, attributes) {
+  attr_name <- sort(grep(attribute_name, names(plot_model$x$layout),
```
Comment (annakrystalli) [inline R/scatter_plot_utils.R:416]: What happens if the `attribute_name` does not match any attributes in `layout`? Or the resulting vector doesn't match the length of `attributes` or the sorting changes how the names map onto the `attributes` elements?

File: tests/testthat/test-plot_step_ahead_model_output.R [hunk 2]
```diff
@@ -141,6 +141,30 @@ test_that("Output", {
...
+  expect_equal(unique(c(attr_test$yaxis, attr_test$yaxis2)), "y")
+
+  plot_test <-
+    plot_step_ahead_model_output(proj_data_q, target_data_us, facet_nrow = 2,
+                                 facet = "model_id", fill_by = "scenario_id",
+                                 facet_scales = "free_y")
+  attr_test <- purrr::map(purrr::flatten(plot_test$x$layoutAttrs), "matches")
+  expect_equal(unique(c(attr_test$xaxis, attr_test$xaxis2)), "x")
+  expect_equal(unique(c(attr_test$yaxis, attr_test$yaxis2)), NULL)
+
```
Comment (annakrystalli) [inline tests/testthat/test-plot_step_ahead_model_output.R:167]: Would be good to add a test for the log transformation also

**Review by annakrystalli — COMMENTED** [review]
Thanks for all the updates @LucieContamin ! I have a couple more questions/suggestions

File: tests/testthat/test-plot_step_ahead_model_output.R (hunk 2 above)
Comment (annakrystalli) [reply tests/testthat/test-plot_step_ahead_model_output.R:167]: Although perhaps this is already tested?

File: R/scatter_plot_utils.R (hunk 1 above)
Comment (annakrystalli) [reply R/scatter_plot_utils.R:416]: It might be good to explain these expectations and restrictions in the comments. Just so if someone else ever had to work with internal source code, the expectations of the function is clear.

Comment (LucieContamin) [reply R/scatter_plot_utils.R]: I updated the documentation:
- add information about the `attribute_name` being extracted from layout
- made is clearer that `attributes` should be a list
- remove `sort` that was just cosmetic.

**Review by annakrystalli — APPROVED** [review]
Thanks @LucieContamin ! All LGTM!
